version: '1'
services:
    test_task_db:
      container_name: test_task_db
      image: postgres:latest
      env_file:
          - .env
      volumes:
          - ./db:/docker-entrypoint-initdb.d/
          - test_volume:/var/lib/postgresql/data
          #- test_task_db:/var/lib/postgresql/data
      networks:
          - test_task
      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
          interval: 5s
          timeout: 5s
          retries: 5

    test_task_redis:
        container_name: test_task_redis
        image: redis:latest
        env_file:
            - .env
        #volumes:
        #    - test_task_redis:/data
        networks:
            - test_task
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1s
            timeout: 3s
            retries: 5

    test_task_django:
        build: ./django
        container_name: test_task_django
        image: test_task_django
        ports:
            - 8000:8000
        env_file:
            - .env
        volumes:
            - ./media:/django/media
            - ./log/:/django/log
        networks:
            - test_task
        depends_on:
            test_task_db:
                condition: service_healthy
            test_task_redis:
                condition: service_healthy
        restart: always

    test_task_app:
        build: ./app
        container_name: test_task_app
        image: test_task_app
        env_file:
            - .env
        volumes:
            - ./log/:/app/log
            - ./media/:/app/media
            - ./orders/:/app/orders
        networks:
            - test_task
        depends_on:
            test_task_db:
                condition: service_healthy
            test_task_redis:
                condition: service_healthy
            test_task_django:
                condition: service_started
        restart: always

    nginx:
        image: nginx:latest
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./django/static/:/opt/django/static/
            - ./media/:/opt/django/media/
        networks:
            - test_task
        depends_on:
            - test_task_app
            - test_task_django
        ports:
            - 80:80

volumes:
    test_volume:
        name: test_volume
#    test_task_db:
#        name: test_task_db
#    test_task_redis:
#        name: test_task_redis

networks:
    test_task:
        name: test_task