# Generated by Django 4.2.7 on 2023-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file_path',
        ),
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/%H/%M/%S', verbose_name='image'),
        ),
    ]
