# Generated by Django 4.2.7 on 2023-11-30 07:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_messages_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.client')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'content"."order',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order')),
            ],
            options={
                'verbose_name': 'order_item',
                'verbose_name_plural': 'order_item',
                'db_table': 'content"."order_item',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='shop.OrderItems', to='shop.item'),
        ),
    ]
