# Generated by Django 4.2.7 on 2023-11-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderitems_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[(0, 'open'), (1, 'closed')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='shop.client'),
        ),
    ]
