# Generated by Django 4.2.7 on 2023-12-01 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_status_alter_order_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='bbd3b9a2-b014-4eed-83d1-259009cfdc30', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(default='bbd3b9a2-b014-4eed-83d1-259009cfdc30', on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(editable=False, through='shop.OrderItems', to='shop.item'),
        ),
    ]
