# Generated by Django 4.2.7 on 2023-12-02 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_client_id_order_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qustions',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('status', models.BooleanField(choices=[(0, 'draft'), (1, 'published')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'questions',
                'verbose_name_plural': 'questions',
                'db_table': 'content"."questions',
            },
        ),
    ]
