FROM python:3.11
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt
WORKDIR /django
COPY . .
VOLUME [ "/app" ]
ENTRYPOINT ["bash", "entrypoint.sh"]